import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar"; // Correct path
import Footer from "./component/Footer"; // Correct path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
      {/* Include the Navbar component */}
      <Navbar />

      {/* Main content */}
      <div className="flex-grow mt-24"> {/* mt-24 to push content below the navbar */}
        {children} {/* Your page content will go here */}
      </div>

      {/* Include the Footer component */}
      <Footer />
    </div>
      </body>
    </html>
  );
}
